locallibrary/catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path(
        'books/<uuid:pk>/return/',
        views.MarkBookAsReturnedView.as_view(),
        name='mark-returned',
    ),
    path(
        'book/<uuid:pk>/renew/',
        views.renew_book_librarian,
        name='renew-book-librarian'
    ),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path(
        "author/<int:pk>/",
        views.AuthorDetailView.as_view(),
        name="author-detail",
    ),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
from datetime import date
from .constants import (
    MAX_LENGTH_NAME,
    MAX_LENGTH_AUTHOR_NAME,
    MAX_LENGTH_ISBN,
    MAX_LENGTH_SUMMARY,
    MAX_LENGTH_UNIQUE_ID,
    LoanStatus
)


class Genre(models.Model):
    """Models representing a book genre"""

    name = models.CharField(
        max_length=MAX_LENGTH_NAME,
        help_text=_('Enter a book genre (e.g. Science Fiction)'),
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(max_length=MAX_LENGTH_NAME)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.CharField(
        max_length=MAX_LENGTH_SUMMARY,
        help_text=_('Enter a brief description of the book'),
    )
    isbn = models.CharField(
        'ISBN',
        max_length=MAX_LENGTH_ISBN,
        unique=True,
        help_text=_(
            '13 Character '
            '<a href="https://www.isbn-international.org/content/what-isbn">'
            'ISBN number</a>'
        ),
    )
    genre = models.ManyToManyField(
        Genre,
        help_text=_('Select a genre for this book'),
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=_(
            'Unique ID for this particular book '
            'across whole library'
        ),
    )
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=MAX_LENGTH_NAME)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    status = models.CharField(
        max_length=1,
        choices=[
            (LoanStatus.MAINTENANCE.value, _(str(LoanStatus.MAINTENANCE.name).capitalize())),
            (LoanStatus.ON_LOAN.value, _(str(LoanStatus.ON_LOAN.name).capitalize())),
            (LoanStatus.AVAILABLE.value, _(str(LoanStatus.AVAILABLE.name).capitalize())),
            (LoanStatus.RESERVED.value, _(str(LoanStatus.RESERVED.name).capitalize())),
        ],
        blank=True,
        default='m',
        help_text='Book availability',
    )

    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=MAX_LENGTH_AUTHOR_NAME)
    last_name = models.CharField(max_length=MAX_LENGTH_AUTHOR_NAME)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

locallibrary/catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog.models import BookInstance

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text=_("Enter a date between now and 4 weeks (default 3).")
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

class RenewBookModelForm(forms.ModelForm):

    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

locallibrary/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic, View
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from catalog.models import Book, Author, BookInstance, Genre
from catalog.constants import LoanStatus, PAGINATION_SIZE
from catalog.forms import RenewBookForm

import datetime

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status__exact=LoanStatus.AVAILABLE.value
    ).count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):

    model = Book
    paginate_by = PAGINATION_SIZE
    context_object_name = 'book_list'
    template_name = 'catalog/book_list.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['some_data'] = 'This is just some data'
        return context


class BookDetailView(generic.DetailView):
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_instances = self.object.bookinstance_set.select_related().all()
        
        # Add a flag to each book instance to indicate if it is available
        for copy in book_instances:
            copy.is_available = (copy.status == LoanStatus.AVAILABLE.value)

        context['book_instances'] = book_instances
        context["can_mark_returned"] = self.request.user.has_perm(
            "catalog.can_mark_returned"
        )

        return context


    def book_detail_view(request, primary_key):
        book = get_object_or_404(Book, pk=primary_key)
        book_instances = book.bookinstance_set.select_related().all()

        context = {
            'book': book,
            'book_instances': book_instances,
        }
        return render(
            request,
            'catalog/book_detail.html',
            context=context
        )

class LoanedBooksByUserListView(generic.ListView):

    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = PAGINATION_SIZE

    def get_queryset(self):
        """Return the books on loan to the current user."""
        return (
            BookInstance.objects.filter(
                borrower=self.request.user,
                status__exact=LoanStatus.ON_LOAN.value
            ).order_by("due_back")
        )

class MarkBookAsReturnedView(PermissionRequiredMixin, View):

    permission_required = "catalog.can_mark_returned"

    def get(self, request, *args, **kwargs):
        book_instance = get_object_or_404(BookInstance, pk=kwargs["pk"])
        return render(
            request,
            "catalog/bookinstance_mark_as_returned.html",
            {
                "bookinstance": book_instance,
            },
        )

    def post(self, request, *args, **kwargs):
        """Process the form submission (confirm return)."""
        book_instance = get_object_or_404(BookInstance, pk=kwargs["pk"])
        book_instance.status = LoanStatus.AVAILABLE.value
        book_instance.borrower = None
        book_instance.save()

        # Redirect to the book detail page after returning
        return redirect("book-detail", pk=book_instance.book.pk)


@login_required
def my_borrowed_books(request):
    borrowed_books = BookInstance.objects.filter(
        borrower=request.user,
        status=LoanStatus.ON_LOAN.value
    )
    context = {
        'borrowed_books': borrowed_books,
        'LoanStatus': LoanStatus,
    }
    return render(request, 'catalog/my_borrowed_books.html', context=context)

class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

class AuthorListView(generic.ListView):
    """Generic class-based view for a list of authors."""

    model = Author
    paginate_by = PAGINATION_SIZE
    context_object_name = "author_list"
    template_name = "catalog/author_list.html"
    queryset = Author.objects.all().order_by("last_name", "first_name")

    def get_context_data(self, **kwargs):
        """Add additional context data to the view."""
        context = super(AuthorListView, self).get_context_data(**kwargs)
        context["can_add_author"] = self.request.user.has_perm(
            "catalog.can_add_author"
        )
        return context

class AuthorDetailView(generic.DetailView):
    """Generic class-based view for an author detail page."""

    model = Author

    def get_context_data(self, **kwargs):
        """Add additional context data to the view."""
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context["book_set"] = Book.objects.filter(author=self.object).order_by(
            "title"
        )
        context["can_update_author"] = self.request.user.has_perm(
            "catalog.change_author"
        )
        context["can_delete_author"] = self.request.user.has_perm(
            "catalog.delete_author"
        )
        return context


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def mark_book_returned(request, bookinstance_id):
    bookinstance = get_object_or_404(BookInstance, id=bookinstance_id)
    if request.method == 'POST':
        bookinstance.status = LoanStatus.AVAILABLE.value
        bookinstance.borrower = None
        bookinstance.due_date = None
        bookinstance.save()
    return redirect('catalog:my_borrowed_books')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    
    book_instance = get_object_or_404(BookInstance, pk=pk)
    
    # If this is a POST request then process the Form data
    if request.method == 'POST':
        form = RenewBookForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
        # process the data in form.cleaned_data as required (here we just write it to the modeldue_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('my-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% load static %}
{% load i18n %}

{% block content %}
  <h1>{% trans "Delete Author" %}</h1>

  <p>{% trans "Are you sure you want to delete the author:" %} <strong>{{ author }}</strong>?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}
{% load i18n %}

{% block content %}
    <h1>{{ author.first_name }} {{ author.last_name }}</h1>
    <p><strong>{% trans "Date of birth" %}:</strong> 
        {{ author.date_of_birth }}
    </p>
    {% if author.date_of_death %}
        <p><strong>{% trans "Date of death" %}:</strong> 
            {{ author.date_of_death }}
        </p>
    {% endif %}

    {% if can_update_author %}
        <a href="{% url 'author-update' author.pk %}">
            {% trans "Update Author" %}
        </a>
    {% endif %}
    {% if can_delete_author %}
        <a href="{% url 'author-delete' author.pk %}">
            {% trans "Delete Author" %}
        </a>
    {% endif %}
    <h2>{% trans "Books by this author" %}</h2>
    <ul>
        {% for book in book_set %}
            <li>
                <a href="{% url 'book-detail' book.pk %}">{{ book.title }}</a>
            </li>
        {% empty %}
            <li>{% trans "No books available." %}</li>
        {% endfor %}
    </ul>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load i18n%}

{% block content %}
<h1>{% trans "Author List" %}</h1>

{% if author_list %}
<ul>
    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">
            {{ author.first_name }} {{ author.last_name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>{% trans "There are no authors in the library." %}</p>
{% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Title:" %} {{ book.title }}</h1>

<p>
    <strong>{% trans "Author:" %}</strong><a href="{% url 'author-detail' book.author.id %}">{{ book.author }}</a>
    <!-- author detail link not yet defined -->
</p>

<p><strong>{% trans "Summary:" %}</strong> {{ book.summary }}</p>

<p><strong>{% trans "ISBN:" %}</strong> {{ book.isbn }}</p>

<p><strong>{% trans "Language:" %}</strong> {{ book.language }}</p>

<p>
    <strong>{% trans "Genre:" %}</strong>
    {{ book.genre.all|join:", " }}
</p>

<div class="instance-list">
    <h4>{% trans "Copies" %}</h4>
    {% for copy in book_instances %}
    <hr>
    <p>
        {{ copy.get_status_display }}
    </p>
    {% if not copy.is_available %}
    <p><strong>{% trans "Due to be returned" %}:</strong> {{ copy.due_back }}</p>
    {% endif %}

    <p><strong>{% trans "Imprint:" %}</strong> {{ copy.imprint }}</p>

    <p class="text-muted">
        <strong>Id:</strong> {{ copy.id }}
    </p>

    {% if copy.status == ON_LOAN and can_mark_returned %}
        <a href="{% url 'mark-returned' copy.id %}" class="btn btn-primary btn-sm">
            {%trans "Mark as Returned" %}
        </a>
    {% endif %}

    {% endfor %}
</div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load i18n%}

{% block content %}
<h1>{% trans "Book List" %}</h1>

{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">
            {{ book.title }}
        </a>
        ({{ book.author }})
    </li>
    {% endfor %}
</ul>
{% else %}
<p>{% trans "There are no books in the library." %}</p>
{% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<h1>{% trans "Renew:"%} {{ book_instance.book.title }}</h1>
<p>{% trans "Borrower:"%} {{ book_instance.borrower }}</p>
<p {% if book_instance.is_overdue %} class="text-danger" {% endif %}>
    {% trans "Due date:"%} {{ book_instance.due_back }}
</p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>

{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<h1>{% trans "Borrowed books" %}</h1>

{% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'book-detail' bookinst.book.pk %}">
                    {{ bookinst.book.title }}
                </a>
                ({{ bookinst.due_back }})
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>{% trans "There are no books borrowed." %}</p>
{% endif %}
{% endblock %}